"""fields and sources: field versions, per-criterion screening data, sources, settings, worker status

Autogenerated against a scratch database at 0001, then reviewed: foreign keys are named, and the data
steps at the end backfill every existing field into version 1 (its criteria become `legacy`, its runs are
linked to it) and seed the sources and the settings row.

Revision ID: 0002
Revises: 0001
"""

import json
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_email", sa.String(length=200), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_results", sa.Integer(), nullable=False),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_check_ok", sa.Boolean(), nullable=True),
        sa.Column("last_check_ms", sa.Integer(), nullable=True),
        sa.Column("last_check_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "worker_status",
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("key_present", sa.Boolean(), nullable=False),
        sa.Column("key_accepted", sa.Boolean(), nullable=True),
        sa.Column("detail", sa.String(length=200), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("role"),
    )
    op.create_table(
        "field_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("field_id", "version"),
    )
    op.create_index(op.f("ix_field_versions_field_id"), "field_versions", ["field_id"], unique=False)
    op.add_column(
        "criteria", sa.Column("kind", sa.String(length=16), server_default="legacy", nullable=False)
    )
    op.add_column("criteria", sa.Column("field_version_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_criteria_field_version_id"), "criteria", ["field_version_id"], unique=False)
    op.create_foreign_key(
        "criteria_field_version_id_fkey",
        "criteria",
        "field_versions",
        ["field_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("criterion_scores", sa.Column("llm_answer", sa.String(length=16), nullable=True))
    op.add_column("criterion_scores", sa.Column("quote", sa.Text(), nullable=True))
    op.alter_column(
        "criterion_scores", "probability", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.add_column("fields", sa.Column("current_version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("fields", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("fields_topic_key"), "fields", type_="unique")
    op.add_column("runs", sa.Column("field_version_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_runs_field_version_id"), "runs", ["field_version_id"], unique=False)
    op.create_foreign_key(
        "runs_field_version_id_fkey", "runs", "field_versions", ["field_version_id"], ["id"]
    )
    op.add_column("screenings", sa.Column("decided_by", sa.String(length=100), nullable=True))
    op.add_column(
        "screenings",
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###
    backfill()


LEGACY_SOURCES = {"names": ["europepmc"], "years": {"from": None, "to": None}}
SOURCES = [("europepmc", True), ("openalex", False), ("arxiv", False)]


def backfill():
    conn = op.get_bind()
    fields = conn.execute(sa.text("select id, name, topic, created_by from fields order by created_at")).all()
    for field_id, name, topic, created_by in fields:
        version_id = uuid.uuid4()
        conn.execute(
            sa.text(
                "insert into field_versions (id, field_id, version, name, topic, sources, note, created_by)"
                " values (:v, :f, 1, :n, :t, cast(:s as jsonb), 'migrated', :u)"
            ),
            {
                "v": version_id,
                "f": field_id,
                "n": name,
                "t": topic,
                "s": json.dumps(LEGACY_SOURCES),
                "u": created_by,
            },
        )
        conn.execute(
            sa.text("update criteria set kind = 'legacy', field_version_id = :v where field_id = :f"),
            {"v": version_id, "f": field_id},
        )
        conn.execute(
            sa.text("update runs set field_version_id = :v where field_id = :f"),
            {"v": version_id, "f": field_id},
        )
    for name, enabled in SOURCES:
        conn.execute(
            sa.text("insert into sources (name, enabled, max_results) values (:n, :e, 100)"),
            {"n": name, "e": enabled},
        )
    conn.execute(sa.text("insert into app_settings (id, contact_email) values (1, null)"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("screenings", "sources")
    op.drop_column("screenings", "decided_by")
    op.drop_constraint("runs_field_version_id_fkey", "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_field_version_id"), table_name="runs")
    op.drop_column("runs", "field_version_id")
    op.create_unique_constraint(op.f("fields_topic_key"), "fields", ["topic"])
    op.drop_column("fields", "archived_at")
    op.drop_column("fields", "current_version")
    op.alter_column(
        "criterion_scores", "probability", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.drop_column("criterion_scores", "quote")
    op.drop_column("criterion_scores", "llm_answer")
    op.drop_constraint("criteria_field_version_id_fkey", "criteria", type_="foreignkey")
    op.drop_index(op.f("ix_criteria_field_version_id"), table_name="criteria")
    op.drop_column("criteria", "field_version_id")
    op.drop_column("criteria", "kind")
    op.drop_index(op.f("ix_field_versions_field_id"), table_name="field_versions")
    op.drop_table("field_versions")
    op.drop_table("worker_status")
    op.drop_table("sources")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
