"""Review panel: reviewer and settings versions, paper files, imported panel results; seeds.

Autogenerated against a database at 0002, reviewed; the seed is appended by hand.

Revision ID: 0003
Revises: 0002
"""

import json
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from research_agent.panel import DEFAULT_EDITOR, default_panel, default_review
from research_agent.schemas import Thresholds

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "sha256"),
    )
    op.create_index(op.f("ix_paper_files_paper_id"), "paper_files", ["paper_id"], unique=False)
    op.create_index(op.f("ix_paper_files_sha256"), "paper_files", ["sha256"], unique=False)
    op.create_table(
        "reviewer_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=30), nullable=False),
        sa.Column("current_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "settings_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("models", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("screening", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fulltext", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("default_panel", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("editor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("imported", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "reviewer_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("perspective", sa.Text(), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["reviewer_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "version"),
    )
    op.create_index(
        op.f("ix_reviewer_versions_profile_id"), "reviewer_versions", ["profile_id"], unique=False
    )
    op.create_table(
        "paper_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("text_source", sa.String(length=16), nullable=False),
        sa.Column("text_reason", sa.Text(), nullable=True),
        sa.Column("text_origin", sa.Text(), nullable=True),
        sa.Column("text_sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("text_truncated", sa.Boolean(), nullable=False),
        sa.Column("text_chars", sa.Integer(), nullable=True),
        sa.Column("editor_verdict", sa.String(length=16), nullable=True),
        sa.Column("editor_reason", sa.Text(), nullable=False),
        sa.Column("disagreements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("editor_call_key", sa.String(length=64), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column("red_flag_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "paper_id"),
    )
    op.create_index(op.f("ix_paper_reviews_paper_id"), "paper_reviews", ["paper_id"], unique=False)
    op.create_index(op.f("ix_paper_reviews_run_id"), "paper_reviews", ["run_id"], unique=False)
    op.create_table(
        "run_reviewers",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("reviewer_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewer_version_id"],
            ["reviewer_versions.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "position"),
    )
    op.create_index(
        op.f("ix_run_reviewers_reviewer_version_id"), "run_reviewers", ["reviewer_version_id"], unique=False
    )
    op.create_table(
        "panel_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_review_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("reviewer_key", sa.String(length=30), nullable=False),
        sa.Column("reviewer_version_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weaknesses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("coverage", sa.Float(), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("call_key", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["paper_review_id"], ["paper_reviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewer_version_id"],
            ["reviewer_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_review_id", "reviewer_key"),
    )
    op.create_index(
        op.f("ix_panel_reports_paper_review_id"), "panel_reports", ["paper_review_id"], unique=False
    )
    op.create_index(
        op.f("ix_panel_reports_reviewer_version_id"), "panel_reports", ["reviewer_version_id"], unique=False
    )
    op.create_table(
        "red_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_review_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=True),
        sa.Column("raised_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["paper_review_id"], ["paper_reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_red_flags_paper_review_id"), "red_flags", ["paper_review_id"], unique=False)
    op.add_column("runs", sa.Column("settings_version_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_runs_settings_version_id"), "runs", ["settings_version_id"], unique=False)
    op.create_foreign_key(
        "runs_settings_version_id_fkey", "runs", "settings_versions", ["settings_version_id"], ["id"]
    )
    # ### end Alembic commands ###
    seed(op.get_bind())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("runs_settings_version_id_fkey", "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_settings_version_id"), table_name="runs")
    op.drop_column("runs", "settings_version_id")
    op.drop_index(op.f("ix_red_flags_paper_review_id"), table_name="red_flags")
    op.drop_table("red_flags")
    op.drop_index(op.f("ix_panel_reports_reviewer_version_id"), table_name="panel_reports")
    op.drop_index(op.f("ix_panel_reports_paper_review_id"), table_name="panel_reports")
    op.drop_table("panel_reports")
    op.drop_index(op.f("ix_run_reviewers_reviewer_version_id"), table_name="run_reviewers")
    op.drop_table("run_reviewers")
    op.drop_index(op.f("ix_paper_reviews_run_id"), table_name="paper_reviews")
    op.drop_index(op.f("ix_paper_reviews_paper_id"), table_name="paper_reviews")
    op.drop_table("paper_reviews")
    op.drop_index(op.f("ix_reviewer_versions_profile_id"), table_name="reviewer_versions")
    op.drop_table("reviewer_versions")
    op.drop_table("settings_versions")
    op.drop_table("reviewer_profiles")
    op.drop_index(op.f("ix_paper_files_sha256"), table_name="paper_files")
    op.drop_index(op.f("ix_paper_files_paper_id"), table_name="paper_files")
    op.drop_table("paper_files")
    # ### end Alembic commands ###


UPLOAD_MAX_MB = 30


def seed(conn):
    """The default panel as version 1 of three reviewers, and review settings version 1. The full-text
    contact comes from the existing contact email; without one Unpaywall is left out (it requires it)."""
    panel = default_panel()
    for reviewer in panel:
        profile_id = uuid.uuid4()
        conn.execute(
            sa.text("insert into reviewer_profiles (id, key, current_version) values (:i, :k, 1)"),
            {"i": profile_id, "k": reviewer["key"]},
        )
        conn.execute(
            sa.text(
                "insert into reviewer_versions (id, profile_id, version, name, perspective, items, model, note)"
                " values (:i, :p, 1, :n, :s, cast(:items as jsonb), null, 'default')"
            ),
            {
                "i": uuid.uuid4(),
                "p": profile_id,
                "n": reviewer["name"],
                "s": reviewer["perspective"],
                "items": json.dumps(reviewer["items"]),
            },
        )
    contact = conn.execute(sa.text("select contact_email from app_settings where id = 1")).scalar()
    fulltext = {**default_review(contact)["fulltext"], "upload_max_mb": UPLOAD_MAX_MB}
    models = {"plan": None, "screen": None, "screen_criteria": None, "extract": None}
    conn.execute(
        sa.text(
            "insert into settings_versions (id, version, models, screening, fulltext, default_panel, editor, note)"
            " values (:i, 1, cast(:m as jsonb), cast(:s as jsonb), cast(:f as jsonb), cast(:d as jsonb),"
            " cast(:e as jsonb), 'default')"
        ),
        {
            "i": uuid.uuid4(),
            "m": json.dumps(models),
            "s": json.dumps(Thresholds().model_dump()),
            "f": json.dumps(fulltext),
            "d": json.dumps([r["key"] for r in panel]),
            "e": json.dumps(DEFAULT_EDITOR),
        },
    )
