// GENERATED by `npm run gen:api` from `research-web openapi`. Do not edit.
export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Invite */
        post: operations["invite_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fields */
        get: operations["list_fields_api_v1_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field */
        get: operations["get_field_api_v1_fields__field_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_v1_runs__run_id__papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_v1_runs__run_id__papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/calls/{call_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Call */
        get: operations["get_call_api_v1_runs__run_id__calls__call_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stages */
        get: operations["list_stages_api_v1_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evals */
        get: operations["list_evals_api_v1_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval */
        get: operations["get_eval_api_v1_evals__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Import */
        post: operations["request_import_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Public liveness probe for the container health check. Touches nothing and reveals nothing.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CallOut */
        CallOut: {
            /** Key */
            key: string;
            /** Role */
            role: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            };
        };
        /** ClaimOut */
        ClaimOut: {
            /** Statement */
            statement: string;
            /** Quote */
            quote: string;
            /** Call Key */
            call_key: string | null;
        };
        /** CriterionOut */
        CriterionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Question */
            question: string;
            /** Version */
            version: number;
            /** Position */
            position: number;
        };
        /** CriterionScoreOut */
        CriterionScoreOut: {
            /** Key */
            key: string;
            /** Question */
            question: string;
            /** Probability */
            probability: number;
            /** Jev Version */
            jev_version: string;
        };
        /** DrawerOut */
        DrawerOut: {
            paper: components["schemas"]["PaperDetail"];
            /** Found By */
            found_by: string;
            /** In Sr */
            in_sr: boolean | null;
            /** Label Source */
            label_source: string | null;
            screening: components["schemas"]["ScreeningOut"];
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
            rank: components["schemas"]["RankCell"] | null;
        };
        /** EvalDetailOut */
        EvalDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            gold_set: components["schemas"]["GoldSetOut"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Agreement */
            agreement: {
                [key: string]: unknown;
            } | null;
        };
        /** EvalHeadline */
        EvalHeadline: {
            retrieval_recall: components["schemas"]["Ratio"] | null;
            cascade_recall: components["schemas"]["Ratio"] | null;
            recommended: components["schemas"]["Recommended"] | null;
            /** Kappa */
            kappa: number | null;
            /** Same Family */
            same_family: boolean | null;
            /** Screened */
            screened: number | null;
        };
        /** EvalSummaryOut */
        EvalSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            gold_set: components["schemas"]["GoldSetOut"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            headline: components["schemas"]["EvalHeadline"];
        };
        /** ExtractCell */
        ExtractCell: {
            /** Claims */
            claims: number;
            /** Quotes Verified */
            quotes_verified: boolean;
        };
        /** FieldOut */
        FieldOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Criteria */
            criteria: components["schemas"]["CriterionOut"][];
        };
        /** GoldSetOut */
        GoldSetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Citation */
            citation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "research" | "eval";
            /** Name */
            name: string;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Run Id */
            run_id: string | null;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MissingCell */
        MissingCell: {
            /**
             * Missing
             * @constant
             */
            missing: true;
        };
        /** PaperDetail */
        PaperDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Year */
            year: number | null;
            /** Doi */
            doi: string;
        };
        /** PaperPage */
        PaperPage: {
            /** Items */
            items: components["schemas"]["PaperRow"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaperRef */
        PaperRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Doi */
            doi: string;
        };
        /** PaperRow */
        PaperRow: {
            paper: components["schemas"]["PaperRef"];
            /** Found By */
            found_by: string;
            /** In Sr */
            in_sr: boolean | null;
            screen: components["schemas"]["ScreenCell"];
            /** Extract */
            extract: components["schemas"]["ExtractCell"] | components["schemas"]["MissingCell"] | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewsCell"] | components["schemas"]["MissingCell"] | null;
            rank: components["schemas"]["RankCell"] | null;
        };
        /** RankCell */
        RankCell: {
            /** Score */
            score: number;
            /** Position */
            position: number;
        };
        /** Ratio */
        Ratio: {
            /** K */
            k: number;
            /** N */
            n: number;
        };
        /** Recommended */
        Recommended: {
            /** Min Confidence */
            min_confidence: number;
            /** Exclude Min Confidence */
            exclude_min_confidence: number;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Role */
            role: string;
            /** Verdict */
            verdict: string;
            /** Relevance */
            relevance: number;
            /** Methods */
            methods: number;
            /** Support */
            support: number;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Call Key */
            call_key: string | null;
        };
        /** ReviewsCell */
        ReviewsCell: {
            /** A */
            a: string | null;
            /** B */
            b: string | null;
            /** Adjudicated */
            adjudicated: boolean;
            /** Adjudicator */
            adjudicator: string | null;
        };
        /** RunCounts */
        RunCounts: {
            /** Screened */
            screened: number;
            /** Kept */
            kept: number;
            /** Dropped */
            dropped: number;
            /** Escalated */
            escalated: number;
            /** In Sr */
            in_sr: number | null;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Name */
            field_name: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gold Set Name */
            gold_set_name: string | null;
            /** Paper Count */
            paper_count: number;
            /** Error */
            error: string | null;
            /** Models */
            models: {
                [key: string]: string;
            };
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            counts: components["schemas"]["RunCounts"];
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Name */
            field_name: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gold Set Name */
            gold_set_name: string | null;
            /** Paper Count */
            paper_count: number;
            /** Error */
            error: string | null;
            /** Models */
            models: {
                [key: string]: string;
            };
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /**
             * Max Papers
             * @default 12
             */
            max_papers: number;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "demo";
        };
        /** ScreenCell */
        ScreenCell: {
            /** Tier */
            tier: string;
            /** Decision */
            decision: string;
            /** Jev Decision */
            jev_decision: string | null;
            /** Llm Decision */
            llm_decision: string | null;
            /** Criteria */
            criteria: {
                [key: string]: number;
            };
        };
        /** ScreeningOut */
        ScreeningOut: {
            /** Tier */
            tier: string;
            /** Decision */
            decision: string;
            /** Jev Decision */
            jev_decision: string | null;
            /** Llm Decision */
            llm_decision: string | null;
            /** Reason */
            reason: string;
            /** Call Key */
            call_key: string | null;
            /** Criteria */
            criteria: components["schemas"]["CriterionScoreOut"][];
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** StageOut */
        StageOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Limits */
            limits: string;
            /**
             * Status
             * @enum {string}
             */
            status: "input" | "measured" | "caveat" | "unmeasured";
            /** Headline */
            headline: string | null;
            /** Caveat */
            caveat: string | null;
            /** Data Link */
            data_link: string | null;
        };
        /** StartRunOut */
        StartRunOut: {
            job: components["schemas"]["JobOut"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** UserPatch */
        UserPatch: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Active */
            active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    invite_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fields_api_v1_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"][];
                };
            };
        };
    };
    get_field_api_v1_fields__field_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                field_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_api_v1_runs__run_id__papers_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort?: string;
                direction?: "asc" | "desc";
                decision?: ("include" | "exclude" | "uncertain") | null;
                tier?: ("jev" | "llm" | "rule") | null;
                escalated?: boolean | null;
                in_sr?: boolean | null;
                criterion?: string | null;
                p_min?: number | null;
                p_max?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_v1_runs__run_id__papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_api_v1_runs__run_id__calls__call_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                call_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_api_v1_stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOut"][];
                };
            };
        };
    };
    list_evals_api_v1_evals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSummaryOut"][];
                };
            };
        };
    };
    get_eval_api_v1_evals__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_import_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
