// GENERATED by `npm run gen:api` from `research-web openapi`. Do not edit.
export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Invite */
        post: operations["invite_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_v1_sources__name__patch"];
        trace?: never;
    };
    "/api/v1/sources/{name}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Source
         * @description Queue a connection check (the worker searches for one result and records the outcome).
         */
        post: operations["check_source_api_v1_sources__name__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Row */
        get: operations["get_settings_row_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_v1_settings_patch"];
        trace?: never;
    };
    "/api/v1/workers/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Worker Status */
        get: operations["worker_status_api_v1_workers_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviewers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviewers
         * @description Reviewers in default-panel order first, then by key.
         */
        get: operations["list_reviewers_api_v1_reviewers_get"];
        put?: never;
        /** Create Reviewer */
        post: operations["create_reviewer_api_v1_reviewers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviewers/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reviewer */
        get: operations["get_reviewer_api_v1_reviewers__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviewers/{key}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reviewer Version */
        get: operations["get_reviewer_version_api_v1_reviewers__key__versions__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviewers/{key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Reviewer */
        post: operations["save_reviewer_api_v1_reviewers__key__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviewers/{key}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Reviewer */
        post: operations["archive_reviewer_api_v1_reviewers__key__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviewers/{key}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Reviewer */
        post: operations["restore_reviewer_api_v1_reviewers__key__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Settings */
        get: operations["get_review_settings_api_v1_settings_review_get"];
        put?: never;
        /** Save Review Settings */
        post: operations["save_review_settings_api_v1_settings_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models Available */
        get: operations["models_available_api_v1_models_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fields */
        get: operations["list_fields_api_v1_fields_get"];
        put?: never;
        /** Create Field */
        post: operations["create_field_api_v1_fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field */
        get: operations["get_field_api_v1_fields__field_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field Version */
        get: operations["get_field_version_api_v1_fields__field_id__versions__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Version */
        post: operations["save_version_api_v1_fields__field_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Field */
        post: operations["archive_field_api_v1_fields__field_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Field */
        post: operations["unarchive_field_api_v1_fields__field_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Criteria
         * @description Queue a criteria test (Jev only, at most 20 papers): the saved current version, or the unsaved
         *     draft in the body. The result arrives in the job's `progress.result`.
         */
        post: operations["test_criteria_api_v1_fields__field_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_v1_runs__run_id__papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_v1_runs__run_id__papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/calls/{call_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Call */
        get: operations["get_call_api_v1_runs__run_id__calls__call_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_v1_papers__paper_id__files_get"];
        put?: never;
        /**
         * Upload File
         * @description Multipart form with one field `file` (a PDF). The size is checked before the body is read.
         */
        post: operations["upload_file_api_v1_papers__paper_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download File */
        get: operations["download_file_api_v1_papers__paper_id__files__file_id__get"];
        put?: never;
        post?: never;
        /** Delete File */
        delete: operations["delete_file_api_v1_papers__paper_id__files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stages */
        get: operations["list_stages_api_v1_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evals */
        get: operations["list_evals_api_v1_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evals/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval */
        get: operations["get_eval_api_v1_evals__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Import */
        post: operations["request_import_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Public liveness probe for the container health check. Touches nothing and reveals nothing.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailableModelOut */
        AvailableModelOut: {
            /** Id */
            id: string;
            /** Provider */
            provider: string | null;
            /** Available */
            available: boolean;
            /** Roles */
            roles: string[];
            /** In Settings */
            in_settings: boolean;
        };
        /** CallOut */
        CallOut: {
            /** Key */
            key: string;
            /** Role */
            role: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            };
        };
        /**
         * ChecklistItemIn
         * @description A checklist item as the reviewer editor sends it; a missing key is generated on save.
         */
        ChecklistItemIn: {
            /** Key */
            key?: string | null;
            /** Text */
            text: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /** Source */
            source?: string | null;
            /**
             * Pass If
             * @default yes
             * @enum {string}
             */
            pass_if: "yes" | "no";
            /** Red Flag If */
            red_flag_if?: ("yes" | "no") | null;
        };
        /** ChecklistItemOut */
        ChecklistItemOut: {
            /** Key */
            key: string;
            /** Text */
            text: string;
            /** Weight */
            weight: number;
            /** Source */
            source: string | null;
            /** Pass If */
            pass_if: string;
            /** Red Flag If */
            red_flag_if: string | null;
        };
        /** ClaimOut */
        ClaimOut: {
            /** Statement */
            statement: string;
            /** Quote */
            quote: string;
            /** Call Key */
            call_key: string | null;
        };
        /**
         * CriteriaTestRequest
         * @description Test the saved current version (`draft` null) or unsaved edits (`draft`).
         */
        CriteriaTestRequest: {
            draft?: components["schemas"]["FieldDraft"] | null;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "demo";
        };
        /** CriterionCell */
        CriterionCell: {
            /** Kind */
            kind: string;
            /** Jev P */
            jev_p: number | null;
            /** Llm */
            llm: string | null;
            /** Quote */
            quote: string | null;
        };
        /** CriterionIn */
        CriterionIn: {
            /** Text */
            text: string;
        };
        /** CriterionOut */
        CriterionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Question */
            question: string;
            /** Version */
            version: number;
            /** Position */
            position: number;
            /** Kind */
            kind?: string;
        };
        /** CriterionRowOut */
        CriterionRowOut: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Jev P */
            jev_p: number | null;
            /** Llm */
            llm: string | null;
            /** Quote */
            quote: string | null;
            /** Decided */
            decided: boolean;
        };
        /** CriterionScoreOut */
        CriterionScoreOut: {
            /** Key */
            key: string;
            /** Question */
            question: string;
            /** Probability */
            probability: number;
            /** Jev Version */
            jev_version: string;
        };
        /** CriterionText */
        CriterionText: {
            /** Key */
            key: string;
            /** Text */
            text: string;
        };
        /** DisagreementOut */
        DisagreementOut: {
            /** Item */
            item: string;
            /** Reviewers */
            reviewers: string[];
            /** Note */
            note: string;
        };
        /** DrawerOut */
        DrawerOut: {
            paper: components["schemas"]["PaperDetail"];
            /** Found By */
            found_by: string;
            /** Sources */
            sources?: string[];
            /** In Sr */
            in_sr: boolean | null;
            /** Label Source */
            label_source: string | null;
            screening: components["schemas"]["ScreeningOut"];
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
            rank: components["schemas"]["RankCell"] | null;
            panel?: components["schemas"]["PanelOut"] | null;
            /** Files */
            files?: components["schemas"]["PaperFileOut"][];
        };
        /** EditorIO */
        EditorIO: {
            /** Model */
            model?: string | null;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** EditorOut */
        EditorOut: {
            /** Verdict */
            verdict: string | null;
            /** Reason */
            reason: string;
            /** Disagreements */
            disagreements: components["schemas"]["DisagreementOut"][];
            /** Call Key */
            call_key: string | null;
        };
        /** EvalDetailOut */
        EvalDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            gold_set: components["schemas"]["GoldSetOut"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Agreement */
            agreement: {
                [key: string]: unknown;
            } | null;
        };
        /** EvalHeadline */
        EvalHeadline: {
            retrieval_recall: components["schemas"]["Ratio"] | null;
            cascade_recall: components["schemas"]["Ratio"] | null;
            recommended: components["schemas"]["Recommended"] | null;
            /** Kappa */
            kappa: number | null;
            /** Same Family */
            same_family: boolean | null;
            /** Screened */
            screened: number | null;
        };
        /** EvalSummaryOut */
        EvalSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            gold_set: components["schemas"]["GoldSetOut"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            headline: components["schemas"]["EvalHeadline"];
        };
        /** ExtractCell */
        ExtractCell: {
            /** Claims */
            claims: number;
            /** Quotes Verified */
            quotes_verified: boolean;
        };
        /** FieldCreate */
        FieldCreate: {
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Include */
            include?: components["schemas"]["CriterionIn"][];
            /** Exclude */
            exclude?: components["schemas"]["CriterionIn"][];
            /** Sources */
            sources: ("europepmc" | "openalex" | "arxiv")[];
            years?: components["schemas"]["Years"];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * FieldDraft
         * @description A field definition as the editor sends it. Criterion keys are generated (i1.., e1..) on save.
         */
        FieldDraft: {
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Include */
            include?: components["schemas"]["CriterionIn"][];
            /** Exclude */
            exclude?: components["schemas"]["CriterionIn"][];
            /** Sources */
            sources: ("europepmc" | "openalex" | "arxiv")[];
            years?: components["schemas"]["Years"];
        };
        /** FieldOut */
        FieldOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Criteria */
            criteria: components["schemas"]["CriterionOut"][];
            /** Current Version */
            current_version?: number;
            /** Archived At */
            archived_at?: string | null;
            current?: components["schemas"]["FieldVersionOut"] | null;
            last_run?: components["schemas"]["FieldRunRef"] | null;
            /** Versions */
            versions?: components["schemas"]["FieldVersionSummary"][];
        };
        /** FieldRunRef */
        FieldRunRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Field Version */
            field_version: number | null;
        };
        /** FieldSave */
        FieldSave: {
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Include */
            include?: components["schemas"]["CriterionIn"][];
            /** Exclude */
            exclude?: components["schemas"]["CriterionIn"][];
            /** Sources */
            sources: ("europepmc" | "openalex" | "arxiv")[];
            years?: components["schemas"]["Years"];
            /**
             * Note
             * @default
             */
            note: string;
            /** Base Version */
            base_version: number;
        };
        /** FieldVersionOut */
        FieldVersionOut: {
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Topic */
            topic: string;
            /** Include */
            include: components["schemas"]["CriterionText"][];
            /** Exclude */
            exclude: components["schemas"]["CriterionText"][];
            /** Legacy */
            legacy: components["schemas"]["CriterionText"][];
            /** Sources */
            sources: string[];
            years: components["schemas"]["Years"];
            /** Note */
            note: string;
            /** Imported */
            imported: boolean;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Count */
            run_count: number;
        };
        /** FieldVersionSummary */
        FieldVersionSummary: {
            /** Version */
            version: number;
            /** Note */
            note: string;
            /** Imported */
            imported: boolean;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Count */
            run_count: number;
            /** Include Count */
            include_count: number;
            /** Exclude Count */
            exclude_count: number;
        };
        /** FulltextIO */
        FulltextIO: {
            /** Sources */
            sources: ("pmc_oa" | "unpaywall" | "upload")[];
            /** Contact */
            contact?: string | null;
            /** Max Chars */
            max_chars: number;
            /**
             * Upload Max Mb
             * @default 30
             */
            upload_max_mb: number;
        };
        /** GoldSetOut */
        GoldSetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Citation */
            citation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "research" | "eval";
            /** Name */
            name: string;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Run Id */
            run_id: string | null;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MissingCell */
        MissingCell: {
            /**
             * Missing
             * @constant
             */
            missing: true;
        };
        /** ModelsAvailableOut */
        ModelsAvailableOut: {
            /** Models */
            models: components["schemas"]["AvailableModelOut"][];
            /** Providers */
            providers: components["schemas"]["ProviderOut"][];
        };
        /** PanelAnswerOut */
        PanelAnswerOut: {
            /** Key */
            key: string;
            /** Text */
            text: string | null;
            /** Source */
            source: string | null;
            /** Weight */
            weight: number | null;
            /** Answer */
            answer: string;
            /** Quote */
            quote: string;
            /** Section */
            section: string;
            /** Red Flag */
            red_flag: boolean;
        };
        /** PanelOut */
        PanelOut: {
            /** Text Source */
            text_source: string;
            /** Text Reason */
            text_reason: string | null;
            /** Text Origin */
            text_origin: string | null;
            /** Text Sections */
            text_sections: string[];
            /** Text Truncated */
            text_truncated: boolean;
            /** Text Chars */
            text_chars: number | null;
            editor: components["schemas"]["EditorOut"];
            /** Reviews */
            reviews: components["schemas"]["PanelReportOut"][];
            /** Red Flags */
            red_flags: components["schemas"]["RedFlagOut"][];
            /** Score */
            score: number | null;
            /** Coverage */
            coverage: number | null;
            /** Red Flag Count */
            red_flag_count: number;
        };
        /** PanelReportOut */
        PanelReportOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Verdict */
            verdict: string;
            /** Score */
            score: number | null;
            /** Coverage */
            coverage: number | null;
            /** Strengths */
            strengths: string[];
            /** Weaknesses */
            weaknesses: string[];
            /** Summary */
            summary: string;
            /** Call Key */
            call_key: string | null;
            /** Answers */
            answers: components["schemas"]["PanelAnswerOut"][];
        };
        /** PaperDetail */
        PaperDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Year */
            year: number | null;
            /** Doi */
            doi: string;
        };
        /** PaperFileOut */
        PaperFileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
            /** Uploaded By Name */
            uploaded_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Can Delete */
            can_delete: boolean;
        };
        /** PaperPage */
        PaperPage: {
            /** Items */
            items: components["schemas"]["PaperRow"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaperRef */
        PaperRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Doi */
            doi: string;
        };
        /** PaperRow */
        PaperRow: {
            paper: components["schemas"]["PaperRef"];
            /** Found By */
            found_by: string;
            /** Sources */
            sources?: string[];
            /** In Sr */
            in_sr: boolean | null;
            screen: components["schemas"]["ScreenCell"];
            /** Extract */
            extract: components["schemas"]["ExtractCell"] | components["schemas"]["MissingCell"] | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewsCell"] | components["schemas"]["MissingCell"] | null;
            rank: components["schemas"]["RankCell"] | null;
            /** Score */
            score?: number | null;
            /** Coverage */
            coverage?: number | null;
            /** Red Flag Count */
            red_flag_count?: number | null;
            /** Text Source */
            text_source?: string | null;
        };
        /** ProviderOut */
        ProviderOut: {
            /** Provider */
            provider: string;
            /** Key Present */
            key_present: boolean;
            /** Key Accepted */
            key_accepted: boolean | null;
        };
        /** RaisedByOut */
        RaisedByOut: {
            /** Reviewer */
            reviewer: string;
            /** Item */
            item: string;
            /** Answer */
            answer: string;
            /** Quote */
            quote: string;
            /** Section */
            section: string;
        };
        /** RankCell */
        RankCell: {
            /** Score */
            score: number;
            /** Position */
            position: number;
        };
        /** Ratio */
        Ratio: {
            /** K */
            k: number;
            /** N */
            n: number;
        };
        /** Recommended */
        Recommended: {
            /** Min Confidence */
            min_confidence: number;
            /** Exclude Min Confidence */
            exclude_min_confidence: number;
        };
        /** RedFlagOut */
        RedFlagOut: {
            /** Text */
            text: string;
            /** Source */
            source: string | null;
            /** Raised By */
            raised_by: components["schemas"]["RaisedByOut"][];
        };
        /** ReviewOut */
        ReviewOut: {
            /** Role */
            role: string;
            /** Verdict */
            verdict: string;
            /** Relevance */
            relevance: number;
            /** Methods */
            methods: number;
            /** Support */
            support: number;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Call Key */
            call_key: string | null;
        };
        /** ReviewSettingsContent */
        ReviewSettingsContent: {
            models: components["schemas"]["RoleModelsIO"];
            screening: components["schemas"]["ScreeningIO"];
            fulltext: components["schemas"]["FulltextIO"];
            /** Default Panel */
            default_panel: string[];
            editor: components["schemas"]["EditorIO"];
        };
        /** ReviewSettingsOut */
        ReviewSettingsOut: {
            current: components["schemas"]["ReviewSettingsVersionOut"];
            /** Versions */
            versions: components["schemas"]["ReviewSettingsSummary"][];
            defaults: components["schemas"]["ReviewSettingsContent"];
        };
        /** ReviewSettingsSave */
        ReviewSettingsSave: {
            models: components["schemas"]["RoleModelsIO"];
            screening: components["schemas"]["ScreeningIO"];
            fulltext: components["schemas"]["FulltextIO"];
            /** Default Panel */
            default_panel: string[];
            editor: components["schemas"]["EditorIO"];
            /**
             * Note
             * @default
             */
            note: string;
            /** Base Version */
            base_version: number;
        };
        /** ReviewSettingsSummary */
        ReviewSettingsSummary: {
            /** Version */
            version: number;
            /** Note */
            note: string;
            /** Imported */
            imported: boolean;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Count */
            run_count: number;
        };
        /** ReviewSettingsVersionOut */
        ReviewSettingsVersionOut: {
            models: components["schemas"]["RoleModelsIO"];
            screening: components["schemas"]["ScreeningIO"];
            fulltext: components["schemas"]["FulltextIO"];
            /** Default Panel */
            default_panel: string[];
            editor: components["schemas"]["EditorIO"];
            /** Version */
            version: number;
            /** Note */
            note: string;
            /** Imported */
            imported: boolean;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Count */
            run_count: number;
        };
        /** ReviewerContent */
        ReviewerContent: {
            /** Name */
            name: string;
            /** Perspective */
            perspective: string;
            /** Model */
            model: string | null;
            /** Items */
            items: components["schemas"]["ChecklistItemOut"][];
        };
        /** ReviewerCreate */
        ReviewerCreate: {
            /** Name */
            name: string;
            /** Perspective */
            perspective: string;
            /** Model */
            model?: string | null;
            /** Items */
            items: components["schemas"]["ChecklistItemIn"][];
            /**
             * Note
             * @default
             */
            note: string;
            /** Key */
            key?: string | null;
        };
        /** ReviewerOut */
        ReviewerOut: {
            /** Key */
            key: string;
            /** Current Version */
            current_version: number;
            /** Archived At */
            archived_at: string | null;
            /** In Default Panel */
            in_default_panel: boolean;
            current: components["schemas"]["ReviewerVersionOut"];
            default: components["schemas"]["ReviewerContent"] | null;
            /** Versions */
            versions?: components["schemas"]["ReviewerVersionSummary"][];
        };
        /** ReviewerSave */
        ReviewerSave: {
            /** Name */
            name: string;
            /** Perspective */
            perspective: string;
            /** Model */
            model?: string | null;
            /** Items */
            items: components["schemas"]["ChecklistItemIn"][];
            /**
             * Note
             * @default
             */
            note: string;
            /** Base Version */
            base_version: number;
        };
        /** ReviewerVersionOut */
        ReviewerVersionOut: {
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Perspective */
            perspective: string;
            /** Model */
            model: string | null;
            /** Items */
            items: components["schemas"]["ChecklistItemOut"][];
            /** Note */
            note: string;
            /** Imported */
            imported: boolean;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Count */
            run_count: number;
        };
        /** ReviewerVersionSummary */
        ReviewerVersionSummary: {
            /** Version */
            version: number;
            /** Note */
            note: string;
            /** Imported */
            imported: boolean;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Run Count */
            run_count: number;
            /** Item Count */
            item_count: number;
        };
        /** ReviewsCell */
        ReviewsCell: {
            /** A */
            a: string | null;
            /** B */
            b: string | null;
            /** Adjudicated */
            adjudicated: boolean;
            /** Adjudicator */
            adjudicator: string | null;
        };
        /** RoleModelsIO */
        RoleModelsIO: {
            /** Plan */
            plan?: string | null;
            /** Screen */
            screen?: string | null;
            /** Screen Criteria */
            screen_criteria?: string | null;
            /** Extract */
            extract?: string | null;
        };
        /** RunCounts */
        RunCounts: {
            /** Screened */
            screened: number;
            /** Kept */
            kept: number;
            /** Dropped */
            dropped: number;
            /** Escalated */
            escalated: number;
            /** In Sr */
            in_sr: number | null;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Name */
            field_name: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gold Set Name */
            gold_set_name: string | null;
            /** Paper Count */
            paper_count: number;
            /** Error */
            error: string | null;
            /** Models */
            models: {
                [key: string]: string;
            };
            /** Field Version */
            field_version?: number | null;
            /** Settings Version */
            settings_version?: number | null;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            counts: components["schemas"]["RunCounts"];
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /** Field Name */
            field_name: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gold Set Name */
            gold_set_name: string | null;
            /** Paper Count */
            paper_count: number;
            /** Error */
            error: string | null;
            /** Models */
            models: {
                [key: string]: string;
            };
            /** Field Version */
            field_version?: number | null;
            /** Settings Version */
            settings_version?: number | null;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Field Id
             * Format: uuid
             */
            field_id: string;
            /**
             * Max Papers
             * @default 12
             */
            max_papers: number;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "demo";
        };
        /** ScreenCell */
        ScreenCell: {
            /** Tier */
            tier: string;
            /** Decision */
            decision: string;
            /** Jev Decision */
            jev_decision: string | null;
            /** Llm Decision */
            llm_decision: string | null;
            /** Criteria */
            criteria: {
                [key: string]: number;
            };
            /** Decided By */
            decided_by?: string | null;
            /** Cells */
            cells?: {
                [key: string]: components["schemas"]["CriterionCell"];
            };
        };
        /** ScreeningIO */
        ScreeningIO: {
            /** Keep Min */
            keep_min: number;
            /** Include Fail Max */
            include_fail_max: number;
            /** Exclude Hit Min */
            exclude_hit_min: number;
            /** Exclude Clear Max */
            exclude_clear_max: number;
        };
        /** ScreeningOut */
        ScreeningOut: {
            /** Tier */
            tier: string;
            /** Decision */
            decision: string;
            /** Jev Decision */
            jev_decision: string | null;
            /** Llm Decision */
            llm_decision: string | null;
            /** Reason */
            reason: string;
            /** Call Key */
            call_key: string | null;
            /** Criteria */
            criteria: components["schemas"]["CriterionScoreOut"][];
            /** Decided By */
            decided_by?: string | null;
            /** Criteria Table */
            criteria_table?: components["schemas"]["CriterionRowOut"][];
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Contact Email */
            contact_email: string | null;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Contact Email */
            contact_email?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Enabled */
            enabled: boolean;
            /** Max Results */
            max_results: number;
            /** Last Check At */
            last_check_at: string | null;
            /** Last Check Ok */
            last_check_ok: boolean | null;
            /** Last Check Ms */
            last_check_ms: number | null;
            /** Last Check Error */
            last_check_error: string | null;
        };
        /** SourcePatch */
        SourcePatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Max Results */
            max_results?: number | null;
        };
        /** StageOut */
        StageOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Limits */
            limits: string;
            /**
             * Status
             * @enum {string}
             */
            status: "input" | "measured" | "caveat" | "unmeasured";
            /** Headline */
            headline: string | null;
            /** Caveat */
            caveat: string | null;
            /** Data Link */
            data_link: string | null;
        };
        /** StartRunOut */
        StartRunOut: {
            job: components["schemas"]["JobOut"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** UserPatch */
        UserPatch: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Active */
            active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatusOut */
        WorkerStatusOut: {
            /** Role */
            role: string;
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Key Present */
            key_present: boolean;
            /** Key Accepted */
            key_accepted: boolean | null;
            /** Detail */
            detail: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Worker Id */
            worker_id: string;
        };
        /** Years */
        Years: {
            /** From */
            from?: number | null;
            /** To */
            to?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    invite_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    patch_source_api_v1_sources__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_source_api_v1_sources__name__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_row_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    patch_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    worker_status_api_v1_workers_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatusOut"][];
                };
            };
        };
    };
    list_reviewers_api_v1_reviewers_get: {
        parameters: {
            query?: {
                /** @description true: also list archived reviewers */
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reviewer_api_v1_reviewers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviewer_api_v1_reviewers__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviewer_version_api_v1_reviewers__key__versions__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_reviewer_api_v1_reviewers__key__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewerSave"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_reviewer_api_v1_reviewers__key__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_reviewer_api_v1_reviewers__key__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_settings_api_v1_settings_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSettingsOut"];
                };
            };
        };
    };
    save_review_settings_api_v1_settings_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSettingsSave"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_available_api_v1_models_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsAvailableOut"];
                };
            };
        };
    };
    list_fields_api_v1_fields_get: {
        parameters: {
            query?: {
                /** @description true: also list archived fields */
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_field_api_v1_fields_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_api_v1_fields__field_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_version_api_v1_fields__field_id__versions__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_version_api_v1_fields__field_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldSave"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_field_api_v1_fields__field_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_field_api_v1_fields__field_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_criteria_api_v1_fields__field_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriaTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                field_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_api_v1_runs__run_id__papers_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort?: string;
                direction?: "asc" | "desc";
                decision?: ("include" | "exclude" | "uncertain") | null;
                tier?: ("jev" | "llm" | "rule") | null;
                escalated?: boolean | null;
                in_sr?: boolean | null;
                criterion?: string | null;
                p_min?: number | null;
                p_max?: number | null;
                decided_by?: string | null;
                source?: ("europepmc" | "openalex" | "arxiv" | "demo") | null;
                has_red_flags?: boolean | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_v1_runs__run_id__papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_api_v1_runs__run_id__calls__call_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                call_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_papers__paper_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperFileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_papers__paper_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The same PDF was already uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperFileOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperFileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_v1_papers__paper_id__files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PDF, as an attachment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_v1_papers__paper_id__files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_api_v1_stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOut"][];
                };
            };
        };
    };
    list_evals_api_v1_evals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSummaryOut"][];
                };
            };
        };
    };
    get_eval_api_v1_evals__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_import_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
