// Dumps the API's OpenAPI schema with `research-web openapi` (venv must be active) and generates TypeScript types.
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const out = join(mkdtempSync(join(tmpdir(), "research-agent-")), "openapi.json");
execFileSync("research-web", ["openapi", "-o", out], {
  stdio: "inherit",
  env: { ...process.env, RESEARCH_WEB_DATABASE_URL: process.env.RESEARCH_WEB_DATABASE_URL ?? "postgresql+psycopg://unused/unused" },
});
const ast = await openapiTS(pathToFileURL(out));
writeFileSync("src/api/schema.d.ts", "// GENERATED by `npm run gen:api` from `research-web openapi`. Do not edit.\n" + astToString(ast));
console.log("wrote src/api/schema.d.ts");
